// Intent type constants.
// Every event that enters director.dispatch() carries one of these as `type`.
// Adding a new intent requires updating both this enum AND the transition
// table in states.js — they're meant to stay in sync.

export const INTENTS = Object.freeze({
  // External — sent by API caller / GM
  START_COMBAT:    "START_COMBAT",
  STOP_COMBAT:     "STOP_COMBAT",

  // External — sent by Turn UI on the GM's client
  DECLARE_COMMAND: "DECLARE_COMMAND",   // body: { command: "Attack" | "Guard" | ... }

  // External — sent by a player client when they finish composing an
  // action locally (composeAction.js). Carries the entire commit bundle
  // so the GM doesn't have to ask back per-pick. See
  // [[director-player-driven-input]].
  ACTION_COMPOSED: "ACTION_COMPOSED",   // body: { bundle: {...} }

  // External — sent by a player client when they click "Take Action" on
  // one of their owned combatants in the turn picker. GM-side TURN_START
  // races this against its own local picker click; whoever clicks first
  // wins.
  TURN_COMBATANT_PICKED: "TURN_COMBATANT_PICKED", // body: { combatantId: string }

  // External — sent by Target Picker
  TARGET_PICKED:   "TARGET_PICKED",     // body: { targetTokenUuids: string[] }
  TARGET_BACK:    "TARGET_BACK",        // user wants to re-pick command

  // External — sent by Action Card buttons (GM-local OR player-owner
  // via socket). Carry no body — the FSM reads ctx.actionResult.
  CONFIRM_ACTION:  "CONFIRM_ACTION",
  CANCEL_ACTION:   "CANCEL_ACTION",

  // External — sent by the owner player's mirror card when they click
  // Invoke Trait or Invoke Bond. GM-side postActionCard validates, pays
  // FP/UP, rerolls, patches its DOM, then broadcasts the updated result
  // back via action-card-invoke-update MENU_OPEN.
  // Body: { type: "trait"|"bond", choice?: "A"|"B"|"AB", bondIndex?: number }
  INVOKE_CHOICE: "INVOKE_CHOICE",

  // External — sent by Reaction UIs (pill on action card OR token-
  // anchored menu) when a player owner clicks Apply / Skip / Pass /
  // a specific reaction blade. Two body shapes share this intent type:
  //
  //   Pre-resolve pill click (action-card.js):
  //     { rowKey, carrierUuid, decision: "apply" | "skip" }
  //   Standalone / post-resolve menu click (standalone-reactions.js,
  //   reaction-menu-player.js):
  //     { reactorActorUuid, rowKey, carrierUuid, decision: "apply" | "pass" }
  //
  // The optional `reactorActorUuid` lets multi-reactor dispatch route
  // a player's click back to the correct GM-side awaitIntent. Older
  // handlers that ignore the field still work — the pill flow has
  // historically been single-reactor (caster = reactor).
  REACTION_CHOICE: "REACTION_CHOICE",

  // External — sent by GM or API to skip the currently playing animation
  // and advance directly to RESOLVE. Also acts as the transition key when
  // the animation controller is already null (i.e. gate already resolved).
  SKIP_ANIMATION:  "SKIP_ANIMATION",

  // Universal escape hatch
  ABORT:           "ABORT",

  // Internal — generated by Director
  TIMEOUT:         "TIMEOUT",
  INTERNAL_DONE:   "INTERNAL_DONE",     // emitted by a synchronous state to advance
  TRIGGER_EMIT:    "TRIGGER_EMIT",      // a reaction trigger fired from RESOLVE
});

export const ALL_INTENT_TYPES = new Set(Object.values(INTENTS));

export function isValidIntent(intent) {
  return !!intent && typeof intent === "object" && ALL_INTENT_TYPES.has(intent.type);
}
