// Intent type constants.
// Every event that enters director.dispatch() carries one of these as `type`.
// Adding a new intent requires updating both this enum AND the transition
// table in states.js — they're meant to stay in sync.

export const INTENTS = Object.freeze({
  // External — sent by API caller / GM
  START_COMBAT:    "START_COMBAT",
  STOP_COMBAT:     "STOP_COMBAT",

  // External — sent by Turn UI on the GM's client
  DECLARE_COMMAND: "DECLARE_COMMAND",   // body: { command: "Attack" | "Guard" | ... }

  // External — sent by Target Picker
  TARGET_PICKED:   "TARGET_PICKED",     // body: { targetTokenUuids: string[] }
  TARGET_BACK:    "TARGET_BACK",        // user wants to re-pick command

  // External — sent by Action Card buttons
  CONFIRM_ACTION:  "CONFIRM_ACTION",
  CANCEL_ACTION:   "CANCEL_ACTION",

  // External — sent by Reaction menus (stubbed in v1)
  REACTION_CHOICE: "REACTION_CHOICE",   // body: { reactorActorId, choice: rowKey | null }

  // Universal escape hatch
  ABORT:           "ABORT",

  // Internal — generated by Director
  TIMEOUT:         "TIMEOUT",
  INTERNAL_DONE:   "INTERNAL_DONE",     // emitted by a synchronous state to advance
  TRIGGER_EMIT:    "TRIGGER_EMIT",      // a reaction trigger fired from RESOLVE
});

export const ALL_INTENT_TYPES = new Set(Object.values(INTENTS));

export function isValidIntent(intent) {
  return !!intent && typeof intent === "object" && ALL_INTENT_TYPES.has(intent.type);
}
